services:
  server:
    build: .
    env_file:
        - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DATABASE=postgres
    restart: always
    extra_hosts:
        - "host.docker.internal:0.0.0.0"
    networks:
      - server_network
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - database

  # Note that this is a debug service.
  database:
    image: postgres:latest
    restart: always
    volumes:
      - server-database-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - server_network
    ports:
      - '5432:5432'

networks:
  server_network:
    driver: bridge

volumes:
  server-database-data: